### ISSUE TITLE
check-style.sh inconsistency with include guards

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2826]
See this [build log](https://travis-ci.com/googleapis/google-cloud-cpp/jobs/211695548#L482):

```
   found: #ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_CPP_COMMON_GRPC_VERSION_INFO_H_
google/cloud/grpc/version_info.h:
expected: #define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GRPC_VERSION_INFO_H_
   found: #define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_CPP_COMMON_GRPC_VERSION_INFO_H_
google/cloud/grpc/version_info.h:
expected: #endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GRPC_VERSION_INFO_H_
   found: #endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_CPP_COMMON_GRPC_VERSION_INFO_H_
google/cloud/grpc/version_info.h has invalid include guards
```

After applying said fix, it no longer complains but then tries to apply the same changes it complains about again, which requires a manual discard:

```diff
diff --git a/google/cloud/grpc/version_info.h b/google/cloud/grpc/version_info.h
index 0b701fe90..dca9bbe7e 100644
--- a/google/cloud/grpc/version_info.h
+++ b/google/cloud/grpc/version_info.h
@@ -12,11 +12,11 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GRPC_VERSION_INFO_H_
-#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GRPC_VERSION_INFO_H_
+#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_CPP_COMMON_GRPC_VERSION_INFO_H_
+#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_CPP_COMMON_GRPC_VERSION_INFO_H_
 
 #define GOOGLE_CLOUD_CPP_COMMON_GRPC_VERSION_MAJOR 0
 #define GOOGLE_CLOUD_CPP_COMMON_GRPC_VERSION_MINOR 1
 #define GOOGLE_CLOUD_CPP_COMMON_GRPC_VERSION_PATCH 0
 
-#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_GRPC_VERSION_INFO_H_
+#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_CPP_COMMON_GRPC_VERSION_INFO_H_
```
